name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run format && bun run build
