name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Build
        run: npm run format && npm run build
